import bcrypt from 'bcryptjs'
const data = {

  users: [
    {
      name: 'Ndeye Amie',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Sibo',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    }, {
      name: 'Rama',
      email: 'rama@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },

  ],
  products: [
    {
      name: ' Jupe',
      slug: 'freejupe',
      category: 'Jupe',
      image: '/images/A1.jpg',
      price: 70,
      brand: 'LDfashion',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Cheveux',
      slug: 'fit-cheveux',
      category: 'Cheveux',
      image: '/images/A4.jpg',
      price: 80,
      brand: 'LDfashion',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Enssemble',
      slug: 'slim-enssemble',
      category: 'Enssemble',
      image: '/images/A6.jpg',
      price: 90,
      brand: 'LDfashion',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: ' Robe',
      slug: 'golf-robe',
      category: 'Robe',
      image: '/images/A7.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: ' Bijou en or',
      slug: 'fit-bijou',
      category: 'Bijou-en or',
      image: '/images/A9.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: ' Chaussure',
      slug: 'classic-chaussure',
      category: 'Chaussure',
      image: '/images/A8.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;